"""add display_name to bots table

Revision ID: 2946e7ba33e5
Revises: bfd81ccec2a1
Create Date: 2025-10-04 02:49:33.143440

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2946e7ba33e5"
down_revision: Union[str, None] = "bfd81ccec2a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots", sa.Column("display_name", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "display_name")
    # ### end Alembic commands ###
